import { sculptToFullGLSLSource, minimalVertexSource } from 'shader-park-core'
import { buildSpCode, SEED_SLOTS } from './spcode'
import type { World } from './world'

/**
 * Raymarched 3D renderer. Shader code is generated by the real Shader Park
 * compiler (sculptToFullGLSLSource), but the render loop is our own minimal
 * loop (modeled on the engine's fragToMinimalRenderer) so we can control:
 *   - backing-store scale: the look is heavy blur, so rendering at ~0.55×
 *     CSS px (effective DPR capped ≈ 1.1) is visually free and cuts fill
 *     rate ~70% on Retina vs the engine's hardcoded full-DPR canvas
 *   - adaptive quality: sustained FPS < 40 steps scale down, > 55 steps up
 *   - pause when document.hidden
 *
 * Screen → sketch-world mapping (z=0 plane, camera at (0,0,-2)):
 *   world x = (px / W - 0.5) * 1.75 * (W / H)
 *   world y = (0.5 - py / H) * 1.75
 *   world r = r_px / H * 1.75
 */

const SCALE_STEPS = [0.4, 0.5, 0.55, 0.6] // ascending; default = index 2
const DEFAULT_STEP = 2
const FPS_LOW = 40
const FPS_HIGH = 55
const ADAPT_WINDOW_MS = 2000
const ADAPT_COOLDOWN_MS = 4000

export class SketchRenderer {
  private gl: WebGL2RenderingContext
  private canvas: HTMLCanvasElement
  private world: World
  private locations = new Map<string, WebGLUniformLocation | null>()
  private scale = SCALE_STEPS[DEFAULT_STEP]
  private step = DEFAULT_STEP
  private raf = 0
  private start = Date.now()
  private lastFrame = performance.now()
  private frameCount = 0
  private windowStart = performance.now()
  private lastAdapt = 0
  private fpsOverlay: HTMLDivElement | null = null

  constructor(canvas: HTMLCanvasElement, world: World) {
    this.canvas = canvas
    this.world = world
    const gl = canvas.getContext('webgl2')
    if (!gl) throw new Error('WebGL2 not available')
    this.gl = gl

    const fragSrc = sculptToFullGLSLSource(buildSpCode(SEED_SLOTS))
    const prog = this.link(fragSrc)
    gl.useProgram(prog)

    // fullscreen triangle (same geometry as the engine's minimal renderer)
    const buf = gl.createBuffer()
    gl.bindBuffer(gl.ARRAY_BUFFER, buf)
    gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([-1, -1, 0, 3, -1, 0, -1, 3, 0]), gl.STATIC_DRAW)
    const coord = gl.getAttribLocation(prog, 'coordinates')
    gl.enableVertexAttribArray(coord)
    gl.vertexAttribPointer(coord, 3, gl.FLOAT, false, 0, 0)

    // cache every uniform location once — no per-frame lookups
    const names = ['time', 'resolution', 'opacity', '_scale', 'mouse']
    for (let i = 0; i < SEED_SLOTS; i++) {
      for (const suffix of ['x', 'y', 'r', 'h', 'cr', 'cg', 'cb']) names.push(`s${i}${suffix}`)
    }
    names.push('mx', 'my')
    for (const n of names) this.locations.set(n, gl.getUniformLocation(prog, n))

    gl.clearColor(1, 1, 1, 0.9)
    gl.enable(gl.DEPTH_TEST)
    this.set1f('opacity', 1)
    this.set1f('_scale', 1)

    if (new URLSearchParams(window.location.search).has('fps')) this.makeFpsOverlay()

    this.resize()
    window.addEventListener('resize', this.resize)
    document.addEventListener('visibilitychange', this.onVisibility)
    this.raf = requestAnimationFrame(this.frame)
  }

  private compile(type: number, src: string): WebGLShader {
    const gl = this.gl
    const sh = gl.createShader(type)
    if (!sh) throw new Error('createShader failed')
    gl.shaderSource(sh, src)
    gl.compileShader(sh)
    if (!gl.getShaderParameter(sh, gl.COMPILE_STATUS)) {
      throw new Error(`shader compile failed: ${gl.getShaderInfoLog(sh)}`)
    }
    return sh
  }

  private link(fragSrc: string): WebGLProgram {
    const gl = this.gl
    const prog = gl.createProgram()
    if (!prog) throw new Error('createProgram failed')
    gl.attachShader(prog, this.compile(gl.VERTEX_SHADER, minimalVertexSource))
    gl.attachShader(prog, this.compile(gl.FRAGMENT_SHADER, fragSrc))
    gl.linkProgram(prog)
    if (!gl.getProgramParameter(prog, gl.LINK_STATUS)) {
      throw new Error(`program link failed: ${gl.getProgramInfoLog(prog)}`)
    }
    return prog
  }

  private set1f(name: string, v: number): void {
    const loc = this.locations.get(name)
    if (loc) this.gl.uniform1f(loc, v)
  }

  /** Backing store = CSS px × min(dpr, 2) × scale, capped at ~1.1× CSS px. */
  private resize = (): void => {
    const dpr = Math.min(window.devicePixelRatio || 1, 2)
    const eff = Math.min(dpr * this.scale, 1.1)
    const w = Math.max(1, Math.round(window.innerWidth * eff))
    const h = Math.max(1, Math.round(window.innerHeight * eff))
    if (this.canvas.width !== w || this.canvas.height !== h) {
      this.canvas.width = w
      this.canvas.height = h
    }
  }

  private onVisibility = (): void => {
    if (!document.hidden) {
      // restart timing so the time uniform doesn't jump
      this.lastFrame = performance.now()
      this.windowStart = this.lastFrame
      this.frameCount = 0
      if (!this.raf) this.raf = requestAnimationFrame(this.frame)
    }
  }

  private makeFpsOverlay(): void {
    const el = document.createElement('div')
    el.style.cssText =
      'position:fixed;top:8px;left:50%;transform:translateX(-50%);z-index:50;' +
      'font:11px/1.4 ui-monospace,monospace;color:rgba(48,42,66,.55);' +
      'background:rgba(255,255,255,.55);backdrop-filter:blur(6px);' +
      'padding:2px 10px;border-radius:99px;pointer-events:none'
    document.body.appendChild(el)
    this.fpsOverlay = el
  }

  private adapt(now: number): void {
    if (now - this.windowStart < ADAPT_WINDOW_MS) return
    const fps = (this.frameCount * 1000) / (now - this.windowStart)
    this.frameCount = 0
    this.windowStart = now
    if (this.fpsOverlay) {
      this.fpsOverlay.textContent = `${fps.toFixed(0)} fps · ${(this.effectiveRatio() * 100).toFixed(0)}%`
    }
    if (now - this.lastAdapt < ADAPT_COOLDOWN_MS) return
    if (fps < FPS_LOW && this.step > 0) {
      this.step--
      this.scale = SCALE_STEPS[this.step]
      this.lastAdapt = now
      this.resize()
    } else if (fps > FPS_HIGH && this.step < SCALE_STEPS.length - 1) {
      this.step++
      this.scale = SCALE_STEPS[this.step]
      this.lastAdapt = now
      this.resize()
    }
  }

  private effectiveRatio(): number {
    const dpr = Math.min(window.devicePixelRatio || 1, 2)
    return Math.min(dpr * this.scale, 1.1)
  }

  private frame = (now: number): void => {
    this.raf = requestAnimationFrame(this.frame)
    if (document.hidden) return
    this.lastFrame = now
    this.frameCount++
    this.adapt(now)

    const gl = this.gl
    const world = this.world
    const W = window.innerWidth || 1
    const H = window.innerHeight || 1

    this.set1f('time', (Date.now() - this.start) / 1000)
    const resLoc = this.locations.get('resolution')
    if (resLoc) gl.uniform2f(resLoc, this.canvas.width, this.canvas.height)

    for (let i = 0; i < SEED_SLOTS; i++) {
      const s = world.seeds[i]
      const p = `s${i}`
      if (s) {
        this.set1f(`${p}x`, (s.x / W - 0.5) * 1.75 * (W / H))
        this.set1f(`${p}y`, (0.5 - s.y / H) * 1.75)
        this.set1f(`${p}r`, Math.max(0.001, (s.r / H) * 1.75))
        this.set1f(`${p}h`, Math.min(1, Math.max(0, (s.amp - 0.03) / 0.17)))
        this.set1f(`${p}cr`, s.color[0])
        this.set1f(`${p}cg`, s.color[1])
        this.set1f(`${p}cb`, s.color[2])
      } else {
        this.set1f(`${p}x`, 999)
        this.set1f(`${p}y`, 999)
        this.set1f(`${p}r`, 0.001)
        this.set1f(`${p}h`, 0)
        this.set1f(`${p}cr`, 0)
        this.set1f(`${p}cg`, 0)
        this.set1f(`${p}cb`, 0)
      }
    }

    if (world.pointerX > -100) {
      this.set1f('mx', ((2 * world.pointerX) / W - 1) * 0.875 * (W / H))
      this.set1f('my', (1 - (2 * world.pointerY) / H) * 0.875)
    } else {
      this.set1f('mx', 999)
      this.set1f('my', 999)
    }

    gl.clear(gl.COLOR_BUFFER_BIT)
    gl.viewport(0, 0, this.canvas.width, this.canvas.height)
    gl.drawArrays(gl.TRIANGLES, 0, 3)
  }
}
